name: learn_kyrgyz
description: "A Flutter app for learning English from Kyrgyz."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  google_fonts: ^6.2.1
  flutter_tts: ^4.0.2
  lottie: ^3.1.2
  flutter_riverpod: ^2.5.1
  flutter_animate: ^4.5.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
